# Generated by Django 4.2.4 on 2023-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreProductAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
