# Generated by Django 4.2.4 on 2023-08-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreProductAPI', '0002_alter_color_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.SmallIntegerField(default=0),
        ),
    ]
