# Generated by Django 4.2.4 on 2023-08-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreProductAPI', '0003_alter_product_reviews_alter_product_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StoreProductAPI.thumbnail'),
        ),
    ]
