# Generated by Django 4.2.4 on 2023-08-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreProductAPI', '0005_alter_thumbnailsize_height_alter_thumbnailsize_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='full',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='full_thumbnails', to='StoreProductAPI.thumbnailsize'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='large',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='large_thumbnails', to='StoreProductAPI.thumbnailsize'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='small',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='small_thumbnails', to='StoreProductAPI.thumbnailsize'),
        ),
    ]
