# Generated by Django 4.2.4 on 2023-08-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreProductAPI', '0006_alter_thumbnail_full_alter_thumbnail_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='thumbnailsize',
            name='url',
            field=models.URLField(max_length=900, null=True),
        ),
    ]
